Add buffer limit
neo-project/neo-vm pull request #512
Opened 2023-10-18 06:41 UTC by Ashuaidehao

The `Buffer` type in VM could occupy up to 2GB memory easily, which was abused by malicious users to slow down public nodes.
This PR try to limit max used size to 100MB of `Buffer` in a single execution.

2023-10-18 07:52 UTC, Liaojinghui commented
Its already exploited?

2023-10-18 07:59 UTC, Ashuaidehao commented
Not found yet, but it can be exploited at any time.

2023-10-18 08:05 UTC, shargon commented
With CAT it's possible to get similar results, please check https://github.com/neo-project/neo-vm/pull/513

2023-10-18 08:11 UTC, roman-khimov commented
This 2GB limit is known for years and was always considered to be OK. Refs. #369, #245.

While I'd still like it to be smaller, additional calculations can affect performance and compatibility now. And 2GB is not a huge amount of memory these days, every phone around can handle it.

2023-10-18 08:36 UTC, Liaojinghui commented
I agree with @roman-khimov. This should not be consisderd an issue unless it can casue OOM like what @vang1ong7ang and @dusmart did https://github.com/neo-project/neo/issues/2527

2023-10-18 08:59 UTC, dusmart commented
> I agree with @roman-khimov. This should not be consisderd an issue unless it can casue OOM like what @vang1ong7ang and @dusmart did [neo-project/neo#2527](https://github.com/neo-project/neo/issues/2527). Or, say, 100 or 500 or 1000 of such transactions could DOS the consensus.

I recall that we indeed abused the `buffer` by using lots of opcodes related to it. Seems that `newbuffer` is still slow enough.

https://github.com/neo-project/neo/issues/2723

2023-10-18 09:20 UTC, roman-khimov commented
Yeah, just wanted to say that some quick allocation/deallocation patterns can be problematic irrespective of the size. This heavily depends on a lot of things (node, runtime, libraries, OS), but I don't think we know of any particularly bad scenario now (`NEWBUFFER` test from neo-project/neo#2723 is worst we know of probably).

2023-10-19 09:01 UTC, shargon requested changes
`MemorySize` is not free during pop

2023-10-19 09:21 UTC, Ashuaidehao commented
> `MemorySize` is not free during pop
Yes, this PR's `MemorySize` was used like memory gas fee, only concern about how much buffer it created. So cannot use "create and drop" mode to evade the limit.

2023-10-20 06:07 UTC, vang1ong7ang commented
2GB is acceptable if it is charged correctly imo

2023-10-25 13:54 UTC, closed without merging